source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.3"

gem "rails"                     , "~> 7.0.4"
gem "pg"                        , "~> 1.1"
gem "puma"                      , "~> 5.0"
gem "tzinfo-data"               , platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap"                  , require: false
gem 'delayed_job'               , '4.1.10'
gem 'delayed_job_active_record' , '4.1.7'
gem 'whenever'                  , '~> 0.9.4'
gem 'active_model_serializers'  , '~> 0.10.2'

group :development, :test do
  gem "debug"                   , platforms: %i[ mri mingw x64_mingw ]
  gem 'pry'                     , '~> 0.13.1'
  gem 'rspec-rails'             , '~> 6.0.0'
  gem 'factory_bot_rails'       , '~> 6.2'
  gem 'faker'                   , '~> 3.0'
end

group :test do
  gem 'simplecov', require: false
end
